services:
  xmrig:
   privileged: true
   user: root
   restart: unless-stopped
   network_mode: host
   cap_add:
    - SYS_ADMIN
    - SYS_RAWIO
   devices:
    - /dev/cpu
    - /dev/mem
   ports:
     - "35689:35689" #api-port
   container_name: xmrig
   volumes:
    - /lib/modules:/lib/modules
   image: ghcr.io/rodrigomaia06/xmrig-0donation:latest
   command: --api-worker-id=(example-name) --http-host=0.0.0.0 --http-port=35689 -o xmr-eu1.nanopool.org:10300 -k --cpu-priority=0 --threads 8
