name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Latest Release Tag
      id: get_release
      run: |
        latest_tag=$(curl -s -H "Accept: application/vnd.github.v3+json" \
                           https://api.github.com/repos/xmrig/xmrig/releases/latest | \
                           jq -r '.tag_name' | cut -c 2-)
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}
        docker tag ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }} ghcr.io/${{ github.repository }}:latest
        
    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}
        docker push ghcr.io/${{ github.repository }}:latest
