name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/xmrig/xmrig/releases/latest | jq -r '.tag_name' | cut -c 2-)

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}/xmrig-0donation:$(date +%s)
